[package]
name = "tauri-todo"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
tauri = { version = "2", features = [] }
tesseron = { path = "../.." }
tesseron-todo-example = { path = "../todo" }
tokio = { workspace = true, features = ["sync"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lints]
workspace = true
